<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

use App\User;
use App\Subscription;

class SubscribeController extends Controller
{
  public function __construct() {
  }

  public function payment(Request $request){

    $selected_plans = $request->input('plan');

    $cost = 0;
    foreach( $selected_plans as $selected_plan){
      $cost = $cost + $this->getPlanByIdOrFail($selected_plan)->amount;
    }

    return view('subscribe')->with( 'cost', $cost/100)->with( compact('selected_plans') )->with('user', Auth::user() );
  }

  private function getPlanByIdOrFail($id)
  {
      $stripe = new \Stripe\Stripe();
      $stripe->setApiKey(env('STRIPE_SECRET'));
      $plans = \Stripe\Plan::all()->data;

      if( ! $plans ) throw new NotFoundHttpException;

      return array_first(array_filter( $plans, function($plan) use ($id) {
          return $id == $plan->id;
      }));
  }

  public function subscribe(Request $request){

    $email = Auth::user()->email;

    if( Auth::user()->stripe_id ){
      $customer_id = Auth::user()->stripe_id;
    } else {
      $customer_id = $this->registerUser($email, $request->input('stripeToken') );
    }

    if( $customer_id ){
      $selected_plans = $request->input('plan');

      $this->subscribePlan($customer_id, $selected_plans);
      return redirect()->route('home')->with('status', implode(",", $selected_plans).' plans subscribed.');
    }

  }

  public function registerUser($email, $stripeToken) {

    $customer = $this->registerUserOnStripe($email, $stripeToken); /// here we are getting customer id given by stripe

    $user = user::find( Auth::user()->id );
    $user->stripe_id = $customer->id;
    $user->card_brand = $customer->sources->data[0]->brand;
    $user->card_last_four =$customer->sources->data[0]->last4;
    $user->save();

    if( $customer ){
      return $customer->id;
    } else {
      return fasle;
    }

  }

  // function to register user on stripe
  public function registerUserOnStripe($email, $stripeToken) {
    try {
      $stripe = new \Stripe\Stripe();
      $stripe->setApiKey(env('STRIPE_SECRET')); // secret key provided by stripe
      $customer = \Stripe\Customer::create(array(
        'email' => $email, // customer email id
        'source' => $stripeToken // stripe token generated by stripe.js
      ));

      if (!empty($customer) && !empty($customer["id"])) {
        return $customer;
      } else {
        return $this->response->responseServerError(Lang::get('User::messages.gateway_error'));
      }
    } catch (\Exception $e) {
      //Log::error("PaymentContractImpl::registerUserOnStripe() there is some exception " . $e->getMessage());
    return false;
    }
  }

  public function subscribePlan($customer_id, $selected_plans) {
    $stripe = new \Stripe\Stripe();
    $stripe->setApiKey(env('STRIPE_SECRET'));

    $plans = [];
    foreach( $selected_plans as $selected_plan){
      array_push($plans, array(
        "plan" => $selected_plan
      ));
    }

    $subscription = \Stripe\Subscription::create(array(
      "customer" => $customer_id,
      "items" => $plans
    ));

    foreach( $selected_plans as $selected_plan){
      $sub = new Subscription;
      $sub->user_id = Auth::user()->id;
      $sub->stripe_id = $subscription->id;
      $sub->stripe_plan = $selected_plan;
      $sub->ends_at = date('Y-m-d H:i:s', $subscription->current_period_end);
      $sub->quantity = 1;
      $sub->save();
    }

    dd($subscription);

  }

  public function cancelSubscription(Request $request){
    $sub_id = $request->input('sub_id');
    $stripe = new \Stripe\Stripe();
    $stripe->setApiKey(env('STRIPE_SECRET'));
    $subscription = \Stripe\SubscriptionItem::retrieve($sub_id);
    //dd($subscription);
    //$subscription = \Stripe\Subscription::retrieve($sub_id);
    $result = $subscription->delete();

    return view('home');
  }



}
